# -*- coding: utf-8 -*-
"""Copia de tarea1_tm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVChCTuHEUT5VAvCj66NJantCLbMMkbT

**PRPBLEMA 1**
**Modelo de crecimiento logístico aplicado a usuarios de una aplicación**

Una aplicación nueva tiene inicialmente  P0= 250 usuarios. Se estima que la cantidad máxima de usuarios que podría alcanzar en ese mercado es K=5000
. Supón que la tasa de crecimiento es r=0.12 por semana.

El modelo logístico discreto es:

 P_t+1=P_t+rP_T(1-P_t/k)

Instrucciones
Simula el crecimiento durante 80 semanas.

Guarda los resultados en un DataFrame con las columnas:

Semana
Usuarios
Grafica la evolución de usuarios en el tiempo.

Agrega una línea horizontal que represente la capacidad máxima.

Repite la simulación para tres valores de la tasa de crecimiento:
 r=0.05, r=0.12, r=0.25

Grafica los tres escenarios en una misma figura.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Parámetros del modelo
p0 = 250          # Población inicial
k = 5000          # Capacidad de carga (K)
n = 100           # Número de periodos (años)

tasas = [0.05, 0.12, 0.25]

tiempos = np.arange(0, n + 1)

# Preparar la visualización
plt.figure(figsize=(10, 6))

# 2. Simulación para cada tasa de crecimiento
for r in tasas:
    p = p0
    poblacion = []

    for t in tiempos:
        poblacion.append(p)
        p = p + r * p * (1 - p / k)

    # Graficar cada serie
    plt.plot(tiempos, poblacion, marker="o", markersize=2, label=f"Tasa r = {r}")

# 3. Estética del gráfico
plt.axhline(y=k, color='red', linestyle="--", alpha=0.6, label=f"Capacidad de carga (K={k})")
plt.xlabel("Tiempo (Años)")
plt.ylabel("Usuarios")
plt.title("Modelo de Crecimiento Logistico")
plt.grid(True, linestyle=':', alpha=0.7)
plt.legend()

plt.show()

# 4. Creación del DataFrame
df = pd.DataFrame({
    "año": tiempos,
    "poblacion_estimada": poblacion
})

df

"""¿Qué ocurre cuando aumenta r? cuando r aumenta, el numero de usuarios aumenta mas rapidamente

¿La población de usuarios crece indefinidamente? No, ya que la cantidad maxima que puede alcanzar en ese mercado es de 5000 usuarios

¿Qué representa la capacidad de carga en este problema? La cantidad maxima que puede alcanzar

**PROBLEMA 2**

Modelo de depreciación de un automóvil

Un automóvil nuevo tiene un valor inicial v=320000 de pesos. Se estima que cada año pierde el 15% de su valor respecto al año anterior.

Este fenómeno puede modelarse con:
 v_t+1=v_t(1-d)

donde:

 v_T es el valor del automóvil en el año t

 d es la tasa de depreciación anual

 t representa el tiempo en años.

Instrucciones
Simula el valor del automóvil durante 15 años.

Guarda los resultados en un DataFrame con las columnas:

Año
Valor del automóvil
Grafica el valor del automóvil en función del tiempo.

Repite la simulación para tres tasas de depreciación:
 d=0.10, d=0.15, d=0.25

Grafica los tres escenarios en una misma figura.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Parámetros base
v0 = 320000
n = 15
tiempos = np.arange(0, n + 1)
tasas = [0.10, 0.15, 0.25]

plt.figure(figsize=(10, 6))

# 2. Simulación múltiple
for d in tasas:
    v = v0
    valor = []

    for t in tiempos:
        valor.append(v)
        v = v * (1 - d)

    # Graficamos cada tasa con una etiqueta descriptiva
    plt.plot(tiempos, valor, marker="o", label=f"Depreciación d = {int(d*100)}%")

# 3. Estética del gráfico
plt.title("Análisis de Sensibilidad: Depreciación del Automóvil")
plt.xlabel("Año")
plt.ylabel("Valor del automóvil ($)")
plt.grid(True, linestyle="--", alpha=0.6)
plt.legend()
plt.show()

#DataFrame
df = pd.DataFrame({
    "Año": tiempos,
    "Valor del automóvil": valor
})
print("Tabla para la tasa del 25%:")
df

"""¿Qué representa el parámetro d? la devaluacion que tiene el automovil como va ocurriendo los años

¿Qué ocurre con el valor del automóvil cuando aumenta d? el automiovil pierde su valor mas rapido

¿El valor del automóvil llega exactamente a cero? No, como el modelo multiplica el valor actual por un factor constante $(1 - d)$, el resultado siempre será una fracción del valor anterior

¿Después de cuántos años el automóvil vale menos de la mitad de su valor inicial cuando  d=015? despues de los 5 años

¿Qué limitaciones tiene este modelo en la vida real? no toma valores externos como que cuando sale de la agencia el automovil pierde valor
"""